<a href="https://colab.research.google.com/github/gargidutta0602/Pytorch/blob/main/Pytorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df = df.drop(["id","Unnamed: 32"],axis = 1)


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

Train Test Split

In [5]:
x = df.drop(["diagnosis"],axis = 1)
y = df["diagnosis"]

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=123)

Data PreProcessing

In [7]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [8]:
lb = LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)


In [9]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,

Numpy Arrey to Pytorch tensors

In [10]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
x_train_tensor.shape

torch.Size([455, 30])

In [12]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [16]:
class MySimpleNN():

  def __init__(self, x):
    self.weights = torch.rand(x.shape[1],1, dtype= torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype= torch.float64, requires_grad=True)

  def forward(self,x):
    z = torch.matmul(x,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss


Important Parameters

In [14]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [38]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range (epochs):

  #forward pass
  y_pred = model.forward(x_train_tensor)

  #loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)

  #backward pass()
  loss.backward()

  #update parametres

  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients

  model.weights.grad.zero_()
  model.bias.grad.zero_()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.8657156714086462
Epoch: 2, Loss: 3.7380006591663997
Epoch: 3, Loss: 3.6088565432974016
Epoch: 4, Loss: 3.4782818264348196
Epoch: 5, Loss: 3.3431598270798104
Epoch: 6, Loss: 3.1984942982058877
Epoch: 7, Loss: 3.0492860894910896
Epoch: 8, Loss: 2.900820141341163
Epoch: 9, Loss: 2.7503744276411064
Epoch: 10, Loss: 2.5942025637966193
Epoch: 11, Loss: 2.436899432542182
Epoch: 12, Loss: 2.2838614046347905
Epoch: 13, Loss: 2.129912936787529
Epoch: 14, Loss: 1.970519036400219
Epoch: 15, Loss: 1.8142072295022416
Epoch: 16, Loss: 1.6651377690942495
Epoch: 17, Loss: 1.524912306395025
Epoch: 18, Loss: 1.3908960547302383
Epoch: 19, Loss: 1.26946272467936
Epoch: 20, Loss: 1.1644729646302152
Epoch: 21, Loss: 1.076486585589957
Epoch: 22, Loss: 1.0050745603055513
Epoch: 23, Loss: 0.9486989641657531
Epoch: 24, Loss: 0.9048900148929394
Epoch: 25, Loss: 0.8708553793737723


In [39]:
model.bias

tensor([-0.1076], dtype=torch.float64, requires_grad=True)

In [40]:
model.weights

tensor([[ 0.4648],
        [ 0.4434],
        [-0.4561],
        [ 0.0049],
        [ 0.2032],
        [ 0.2831],
        [-0.4341],
        [-0.0692],
        [ 0.4650],
        [-0.2427],
        [-0.4474],
        [ 0.1573],
        [-0.0656],
        [ 0.1342],
        [-0.1774],
        [ 0.2754],
        [ 0.3591],
        [-0.1465],
        [ 0.6817],
        [ 0.4764],
        [ 0.2960],
        [-0.0628],
        [-0.4174],
        [ 0.1712],
        [ 0.3156],
        [ 0.0189],
        [ 0.3525],
        [-0.2145],
        [-0.1450],
        [-0.3892]], dtype=torch.float64, requires_grad=True)

Evaluation

In [41]:
#model Evaluation

with torch.no_grad():
  y_pred = model.forward(x_test_tensor)

In [42]:
y_pred = (y_pred>0.5).float()
accuracy = (y_pred == y_test_tensor).float().mean()
print(f'Accuracy:{accuracy.item()}')


Accuracy:0.5541704893112183
